### ISSUE TITLE
model.py line 453 IndexError: Dimension out of range (expected to be in range of [-1, 0], but got 1)

### ISSUE THREAD

**Issue by FriedaSmith** [mayank-git-hub/ETE-Speech-Recognition#1]
Hello. When I run your code, it had an exception in `ilter_banks = torch.matmul(pow_frames, fbank.transpose(1, 0))`:
`IndexError: Dimension out of range (expected to be in range of [-1, 0], but got 1)
`
Thanks and regards

**Comment by mayank-git-hub** [comment]
Thank you for using the repository!

The error means that fbank is a 1 dimension torch tensor, whereas the way I have initialized it on line 397 in model.py shows it to be 2 dimensional. 

Did you change some parts of the code? If so, then could you please send it here, I would have a look into it.

**Comment by FriedaSmith** [comment]
I only delete  `num_cuda` in `config.py` beacuse `NameError: name 'num_cuda' is not defined`

**Comment by mayank-git-hub** [comment]
I guess you meant added num_cuda. I will add the specific_cuda.py file in the repository, it will clear out some of the errors.

But related to the fbank part, I am not sure why you are getting the error. Let me re-run the code and check if it works fine on my PC. I will get back to you.

**Comment by mayank-git-hub** [comment]
I have added the specific_config.py file in the repository. You will have to set the path for the dataset there. 

I hope it solves some of the errors. 

I will get back to you regarding the fbank error.

**Comment by mayank-git-hub** [comment]
I guess when you removed config.num_cuda from the line 412 in model.py which is

self.fbank = [fbank.to(torch.device('cuda:'+str(i))) for i in range(len(config.num_cuda.split(',')))]

You might have removed the list. That is why the fbank which was a list of 2 dimension tensor, became a 2 dimension tensor, and one dimension was removed in model.p[y line 418. 

I think if you revert the changes you made it should work now.

**Comment by FriedaSmith** [comment]
Thank you very much. It's the problem of ` num_cuda`. I can run normally according to your configuration in `specific_config.py`.

**Comment by mayank-git-hub** [comment]
Glad I could help. I would close the issue now.
