### ISSUE TITLE
model.py line 501 RuntimeError: result type Byte can't be cast to the desired output type Bool

### ISSUE THREAD

**Issue by FriedaSmith** [mayank-git-hub/ETE-Speech-Recognition#2]
Excuse me. 
In the `model.py`, line 501:  `return ys_mask.unsqueeze(-2) & m`
In training, it made this error.
The error information: `RuntimeError: result type Byte can't be cast to the desired output type Bool`
I'm so confused, plz help me!!!!

**Comment by mayank-git-hub** [comment]
I believe you will have to downgrade your torch. torch earlier didn't support type Bool, so the code has been written in Byte type. I believe torch 1.1.0 should work.

**Comment by FriedaSmith** [comment]
Thank you very much. It's the issue of torch version.

**Comment by mayank-git-hub** [comment]
Glad to be of help!.
