### ISSUE TITLE
Two GPUs Problem

### ISSUE THREAD

**Issue by FriedaSmith** [mayank-git-hub/ETE-Speech-Recognition#4]
Hello.I want to use 2 GPUs to train model.
`num_cuda = '0,1'` in  `specific_config.py`.
The following error occurred:
`RuntimeError: Tensor for argument #2 'targets' is on CPU, but expected it to be on GPU (while checking arguments for ctc_loss_gpu)
`

**Comment by mayank-git-hub** [comment]
Can you check if in specific_config.py use_cuda is set to True?

**Comment by FriedaSmith** [comment]
Sorry, it's a configuration problem.

**Comment by mayank-git-hub** [comment]
That is fine! Hope it works on multiple GPUs.
