### ISSUE TITLE
Not found: unknown field name '/cache/unigram_model/unigram' in TrainerSpec

### ISSUE THREAD

**Issue by hulk12321** [mayank-git-hub/ETE-Speech-Recognition#7]
Hello,I met an error "Not found: unknown field name '/cache/unigram_model/unigram' in TrainerSpec" when I run 'python main.py train'.
It ouccred when the program ran to 'create_unigram_model()' , and I guessed there is a file named 'unigram' missing. Can you please tell me how to solve the problem?

**Comment by mayank-git-hub** [comment]
Hello @hulk12321 ,

In specificConfig.py, set the path to where you would want to save the unigram model in "cache_dir".
Then run - 

python main.py genUnigram

Please follow the steps in the docs to train your model.
